#!/bin/bash

MODEL_FILE="microcin.pm"
PROPERTIES_FILE="microcin.csl"
CONSTS_FILE="const.txt"
RESULTS_FILE="res.txt"

if [ $# -ge 1 ]; then MODEL_FILE=$1; fi
if [ $# -ge 2 ]; then PROPERTIES_FILE=$2; fi
if [ $# -ge 3 ]; then CONSTS_FILE=$3; fi
if [ $# -ge 4 ]; then RESULTS_FILE=$4; fi

CONSTS=$(cat $CONSTS_FILE | tr -d '\n') 
RESULTS="-exportresults $RESULTS_FILE"
OTHER=""
ADDITIONAL=${*:5}         # additional command line arguments

ARGS="$MODEL_FILE $PROPERTIES_FILE $CONSTS $RESULTS $OTHER $ADDITIONAL"

echo "prism "$ARGS
prism $ARGS

